server:
  port: 8081

spring:
  application:
    # 应用名称
    name: @artifactId@
  profiles:
    # 环境配置
    active: @active@
  cloud:
    polaris:
      address: grpc://${POLARIS_HOST:twelvet-polaris}:${POLARIS_PORT:8091}
      namespace: ${spring.profiles.active}
      config:
        # 自定义配置文件格式，非polaris配置
        file-extension: yml
  config:
    import:
      - optional:polaris:tw:twelvet-app-${spring.profiles.active}.${spring.cloud.polaris.config.file-extension}
      - optional:polaris:tw:${spring.application.name}-${spring.profiles.active}.${spring.cloud.polaris.config.file-extension}