name: 🐛 Bug report
description: Report a bug to help us improve twelvet
title: "[Bug]: "
labels: [bug]
assignees:
  - twelvet-s
body:
  - type: input
    id: twelvet
    attributes:
      label: twelvet Version
      description: Please enter the current version of the project you are using.
      placeholder: 3.0.0
    validations:
      required: true
  - type: input
    id: node
    attributes:
      label: Node Version
      description: Please enter the current version of Node.js you are using.
      placeholder: v16.15.0
    validations:
      required: true
  - type: input
    id: java
    attributes:
      label: JDK Version
      description: Please enter the current version of JDK you are using.
      placeholder: JDK 17
    validations:
      required: true
  - type: dropdown
    id: reappearance
    attributes:
      label: Does it still exist
      description: Can this bug be reproduced on the master branch?
      options:
        - Yes
        - No
        - Not tested
    validations:
      required: true
  - type: textarea
    id: desc
    attributes:
      label: Bug Description
      description: Please briefly describe the bug and its replication process.
      placeholder: |
        1. Firstly...
        2. And then...
    validations:
      required: true
  - type: textarea
    id: advise
    attributes:
      label: Modification suggestions.
      description: Do you have any good suggestions or modification plans to offer us?
