name: 🚀 Feature request
description: Suggest an idea for twelvet
title: "[Feature]: "
labels: [feature]
assignees:
  - twelvet-s
body:
  - type: textarea
    id: desc
    attributes:
      label: Function description and necessity description
      description: What convenience do you think this new feature will bring to the framework.
      placeholder: |
        1. Firstly...
        2. And then...
    validations:
      required: true
  - type: textarea
    id: advise
    attributes:
      label: Suggestions and solutions
      description: You can provide us with good suggestions or modification plans。
