name: test

on:
  push:
    branches: [ master, master-boot-3 ]
  pull_request:
    branches: [ master, master-boot-3 ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 17 ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'zulu'

      - name: mvn spring-javaformat:validate
        run: mvn spring-javaformat:validate

      - name: mvn clean install
        run: mvn clean install

      - name: into docker
        run: cd docker

      - name: chmod
        run: ls && chmod 751 deploy.sh && deploy.sh init

      - name: Start Server
        run: docker-compose -f docker-compose.yml up -d

