name: test

on:
  push:
    branches: [ master, master-boot-3 ]
  pull_request:
    branches: [ master, master-boot-3 ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 17 ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'zulu'

      - name: mvn spring-javaformat:validate
        run: mvn spring-javaformat:validate

      - name: mvn clean install
        run: mvn clean install

      - name: into docker
        run: cd docker

      - name: cp
        run: cp data/sql/twelvet.sql ./mysql/db && cp data/sql/twelvet_nacos.sql ./mysql/db && cp twelvet-gateway/target/twelvet-gateway.jar ./twelvet/gateway/jar && cp twelvet-auth/target/twelvet-auth.jar ./twelvet/auth/jar && cp twelvet-server/twelvet-server-system/target/twelvet-server-system.jar ./twelvet/server/system/jar

      - name: Start Server
        run: docker-compose -f docker/docker-compose.yml up -d

